const DEVIS = {
"_id":"GabcZB9Jg2bsAhSov",
"created_at":1595244066574,
"libelle":"",
"entreprise_id":"",
"client_id":"",
"elements":[
"pnRuvjM5Lk6LMX3ro",
"Qy8QNsmqTKGK6Tzgh",
"sE8LHiyYtAozqhKKW",
"3GfFHZjSrKXd55x5W",
"dqXtDgDPHrhFRuMJs",
"AeT4yA5aQ8neCGqgy",
"hKdnv6WY8BziTRnLM",
"zNB9eYodKniy2MPd9",
"ejzakZceuW432HzBE",
"fztcTn6wE7zFvvNwR",
"P4kDnYy85LCGwMsPo",
"x4XaCWa9WBTw2dPZz",
"vX5SKwTKHrKf7SCzg",
"xFuEKKpq92FkbuzY4",
"9cn28qoYFYCMTasGh",
"NyEoMcMnyquawcTNy",
"Ksou4x4463Yi5FguJ",
"fJLMMMFcpL8pYWKou",
"yMdG7cCsswskiWG8o",
"FrgcpETNkW8mWhDHr",
"bfEHEFtmfcaroYLk5",
"8aEEnnL5paPLtu9FG",
"WddzZKJCykR5DCsZ6",
"5WfEAGjEhJDSz6Cmc",
"nbpXqHxE68Xw65zpB",
"kBsAFZbCLE7fq89hw",
"q3KqMFHZxwxDBi8oM",
"3MBhNozbEEcdK2Xct",
"jN9LWutbEgRm635Ys",
"PtchCLHofAXzb3ACq",
"T5hN8Ws2m9ktWx7fH",
"LkXAuZs8aDSGRZaDk",
"S4AGDJ9Z2KA2vdxbz",
"WvgJCpANaRAidbGWG",
"tPYSRgaCNwimssybj",
"KgmpNYanP8ZeuMq3s",
"8YpF53hGhsGhrZFSx",
"JLXzQqfy6WiPERrFN",
"pka5KSANZQhHcKu4t",
"Kpo6dKEWZ8tqoq6ZC",
"DncG4BRd9CRnCvfmj",
"yLACgcCgqkatzuFfd",
"JxfjFerDi3xqnbcE2",
"K7Z9SKmWMia3so6SC",
"AdTEJKuiMRRFX4XiM",
"TWAgRS6SYGorC6xfw",
"WNBwwg4R7hxrrkvXn",
"zEK7zGsAZm3SvXNXc",
"cpbXqWuMgxHTb6JRk",
"2vgRh7hGY6FL3YhRp",
"HvnFcMQkgpvvHYr52",
"9N4LT54f8hGjkCFNf",
"6ynLrghep2La3HCsS",
"YSgzvr98BgPf7EB4E",
"dh3P6f4BBcbMsJFTn",
"jEvuXPiNYwhyttPMo",
"j8wuQ2gufqKbbxS5r",
"rdk6C5YRFPSqt2gcn",
"M4YMdfWRztKQARi4b",
"7yvfaP6haifxd2rTz",
"EdsZJk2mY9d329rsd",
"B4n7FxnJFmiQoLGhD",
"2j4k3qGijetTDqjB2",
"9QhDtGA8E3Fg3mroz",
"rhaiPWJPurgFbEQuS",
"HMSqQESsFsk5mWuP9",
"3ouyaLPHMoEme6WEh",
"yN45tnXihFhv9zD3C",
"x9SeoPKqbcKRQErHh",
"7WqHLcZyK7wKaq5LR",
"y9ciExqKCc2Y6hxTK",
"aGoaCL7sudgXGTApu",
"A9Z8drBcFbdckzn2o",
"rw2H4CygCfCjGeAy9",
"mbH5YBu7nn97NtdRB",
"cDcF7YTFzKZ4dJGHP",
"zNkhu33aqqv6oMB6F",
"rW2pe4kqGvRbQ47mP",
"hPDGaSauGewYuR6Hq",
"h3WtaPmDjfwKYTEsx",
"8i95pgbY5NdAmufJw"
],
"user_id":"gofcmeaAhnAdyXFTf",
"client":"26XC5jn3R6wPYhWCi",
"entreprise":"nnBWprTkd5wiivGPM",
"titre":"DECKVENTURE",
"dynamique":true,
"contractuel":true,
"tjm":"150",
"unite":"1/2 jour",
"password":"test"
}

const ELEMENTS = [
{
"_id":"kBsAFZbCLE7fq89hw",
"created_at":1595667734183,
"libelle":"Elaboration du devis",
"prix":"2",
"titre":0,
"sans_interaction":false,
"numerique":false,
"logiques":[
"Y8cTxmFeRG84yX4ar"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf",
"titre_lvl":"1"
},
{
"_id":"TuFXrPjMEm9k5QCsf",
"created_at":1595667734183,
"libelle":"Accompagnement conception",
"prix":"0",
"titre":0,
"sans_interaction":false,
"numerique":false,
"logiques":[
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf",
"titre_lvl":"0"
},
{
"_id":"nbpXqHxE68Xw65zpB",
"created_at":1595667734183,
"libelle":"Accompagnement conception",
"prix":"2",
"titre":0,
"sans_interaction":false,
"numerique":false,
"logiques":[
"LFFd8wz3RSdCtXzjk"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf",
"titre_lvl":"1"
},
{
"_id":"5WfEAGjEhJDSz6Cmc",
"created_at":1595668185790,
"libelle":"cahier des charges maquette",
"prix":"2",
"titre":0,
"sans_interaction":false,
"numerique":false,
"logiques":[
"KJkPEw2gMJqEQDejP"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf",
"titre_lvl":"1"
},
{
"_id":"Sk96LT397ev2BfQMn",
"created_at":1595668185790,
"libelle":"jjjjj",
"prix":"",
"titre":0,
"sans_interaction":true,
"numerique":false,
"logiques":[
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf",
"titre_lvl":"1"
},
{
"_id":"dpRYqjzifbXSK9tDk",
"created_at":1595668185790,
"libelle":"jjjjj",
"prix":"",
"titre":0,
"sans_interaction":true,
"numerique":false,
"logiques":[
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf",
"titre_lvl":"1"
},
{
"_id":"3GfFHZjSrKXd55x5W",
"created_at":1595685610932,
"libelle":"En ligne et hors ligne",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"m8bX6jSBikQoi22qs",
"oTJkJgFvwsP6bohDC"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"sE8LHiyYtAozqhKKW",
"created_at":1595685610932,
"libelle":"Uniquement hors ligne",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"K5xAq7FiHMq2buYPN",
"EyxwRbZ5ojrq2a8db"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"Qy8QNsmqTKGK6Tzgh",
"created_at":1595685610932,
"libelle":"Uniquement en ligne",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"57LvNr9yJ7WAkqsjE",
"FxfaLnnrhQ8AME5nd"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"fztcTn6wE7zFvvNwR",
"created_at":1595685610932,
"libelle":"Sauvegarde ",
"prix":0,
"titre_lvl":"2",
"sans_interaction":true,
"numerique":false,
"logiques":[
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"hKdnv6WY8BziTRnLM",
"created_at":1595685610932,
"libelle":"Accompagnement conception",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"gfvuTiegbkhZn7xTt"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"NyEoMcMnyquawcTNy",
"created_at":1595685610932,
"libelle":"Indices ",
"prix":0,
"titre_lvl":"1",
"sans_interaction":true,
"numerique":false,
"logiques":[
"gfvuTiegbkhZn7xTt"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"AeT4yA5aQ8neCGqgy",
"created_at":1595685610932,
"libelle":"Design",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"P4kDnYy85LCGwMsPo",
"created_at":1595685610932,
"libelle":"Sauvegarde",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"3Hi2ja7tTLs8XyWTZ"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"8aEEnnL5paPLtu9FG",
"created_at":1595685610932,
"libelle":"Interface de saisie compatiblité multi navigateur",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"gru7vioNrCY6NyCNx"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"x4XaCWa9WBTw2dPZz",
"created_at":1595685610932,
"libelle":"Persistance de la sauvegarde",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"egdzDjDpL5QbuGikL"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"vX5SKwTKHrKf7SCzg",
"created_at":1595685610932,
"libelle":"Appel de piste audio ",
"prix":0,
"titre_lvl":"1",
"sans_interaction":true,
"numerique":false,
"logiques":[
"gfvuTiegbkhZn7xTt"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"xFuEKKpq92FkbuzY4",
"created_at":1595685610932,
"libelle":"Light",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"sRvZNYkyD4k6rpjMf",
"jrM2ChjDJvBnLSW9p"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"Ksou4x4463Yi5FguJ",
"created_at":1595685610932,
"libelle":"Light",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"w7zyAXjJTjjLcPL9N",
"dBgyagHuftNZcEt7B"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"9cn28qoYFYCMTasGh",
"created_at":1595685610932,
"libelle":"Complet",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"Awov4KoC6vroiqSp9",
"g9XfgtgZcyHPMvDrS"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"ejzakZceuW432HzBE",
"created_at":1595685610932,
"libelle":"Score",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"fJLMMMFcpL8pYWKou",
"created_at":1595685610932,
"libelle":"Complet",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"2szN82YwY3MHPqKBg",
"jQHqu6f8K9G2mkQqK"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"zNB9eYodKniy2MPd9",
"created_at":1595685610932,
"libelle":"Chronometre",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"gfvuTiegbkhZn7xTt"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"yMdG7cCsswskiWG8o",
"created_at":1595685610932,
"libelle":"Nombre de scenario ",
"prix":0,
"titre_lvl":"1",
"sans_interaction":false,
"numerique":true,
"logiques":[
"gfvuTiegbkhZn7xTt"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"FrgcpETNkW8mWhDHr",
"created_at":1595685610932,
"libelle":"Interface de saisie (prix du scenario/2)",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"4NEmTkD43XFxTfBnM"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"bfEHEFtmfcaroYLk5",
"created_at":1595685610932,
"libelle":"Interface de saisie responsive",
"prix":0,
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"8qaknNnDwfLMqu2AF"
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"dqXtDgDPHrhFRuMJs",
"created_at":1595685610932,
"libelle":"Autre ",
"prix":0,
"titre_lvl":"2",
"sans_interaction":true,
"numerique":false,
"logiques":[
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"pnRuvjM5Lk6LMX3ro",
"created_at":1595685612648,
"libelle":"Fonctionnement ",
"prix":0,
"titre_lvl":"2",
"sans_interaction":true,
"numerique":false,
"logiques":[
],
"dynamique":true,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"q3KqMFHZxwxDBi8oM",
"created_at":1595839745248,
"libelle":"Architecture de l'application",
"prix":"4",
"titre_lvl":"1",
"sans_interaction":false,
"numerique":false,
"logiques":[
"x2XkuZ2sCkTgdxoid"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"3MBhNozbEEcdK2Xct",
"created_at":1595839838239,
"libelle":"Mise en place de la BDD",
"prix":"4",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"236yCKbRfM7ahngjZ"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"jN9LWutbEgRm635Ys",
"created_at":1595839857432,
"libelle":"stockage de piste audio",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"RP49eds5bF5C2kCu2"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"PtchCLHofAXzb3ACq",
"created_at":1595839876588,
"libelle":"stockage d'images",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"ai63YZZo3xu8eQpBD"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"JxfjFerDi3xqnbcE2",
"created_at":1595840479256,
"libelle":"Fonctionalitées",
"prix":"",
"titre_lvl":"2",
"sans_interaction":true,
"numerique":false,
"logiques":[
"rafeNpQqJrdePqd44"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"yLACgcCgqkatzuFfd",
"created_at":1595840526774,
"libelle":"Pavé numerique (5 vues)",
"prix":"1",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"jDbcsjXzFhZ3zHBDc"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"pka5KSANZQhHcKu4t",
"created_at":1595840609338,
"libelle":"Preface scenario",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"MeAE4ArDEy2qdE3as"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"JLXzQqfy6WiPERrFN",
"created_at":1595840610072,
"libelle":"Accueil avec scroll infini",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"Z53XrocAbDMdbCbmA"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"DncG4BRd9CRnCvfmj",
"created_at":1595840718313,
"libelle":"Accueil scenario",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"t78PCyh8H7k3n47pX"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"LkXAuZs8aDSGRZaDk",
"created_at":1595840753007,
"libelle":"Accueil avec scroll infini",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"HF9scDe2N8PBeByev"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"S4AGDJ9Z2KA2vdxbz",
"created_at":1595840766688,
"libelle":"Preface scenario",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"6aGCM2GpvjQCoekxK"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"Kpo6dKEWZ8tqoq6ZC",
"created_at":1595840772587,
"libelle":"Menu indice",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"45eP9sbfZPW7ZTtSn"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"T5hN8Ws2m9ktWx7fH",
"created_at":1595840780620,
"libelle":"Vues",
"prix":"",
"titre_lvl":"2",
"sans_interaction":true,
"numerique":false,
"logiques":[
"CnAd6PvvmRGLYbtXn"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"WvgJCpANaRAidbGWG",
"created_at":1595840835479,
"libelle":"Accueil scenario",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"EiTYSAyhHS2kYLuLv"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"tPYSRgaCNwimssybj",
"created_at":1595840909062,
"libelle":"Menu scenario",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"hd3fLoKxF4haA6sH4"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"KgmpNYanP8ZeuMq3s",
"created_at":1595840942407,
"libelle":"Pavé numerique (5 vues)",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"ZY5CkfgF4DLWDxaeE"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"8YpF53hGhsGhrZFSx",
"created_at":1595840986679,
"libelle":"Design",
"prix":"",
"titre_lvl":"2",
"sans_interaction":true,
"numerique":false,
"logiques":[
"eh7XLXNEX7RAmwrh7"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"K7Z9SKmWMia3so6SC",
"created_at":1595841351767,
"libelle":"Lancement d'une bande son lorsqu'on entre un numéro",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"Fi7hmmXc6rQNWgiHx"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"AdTEJKuiMRRFX4XiM",
"created_at":1595841471689,
"libelle":"Poppup personnage lorsqu'on entre un numéro",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"9YuCfmXdt7vTtSb9k"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"TWAgRS6SYGorC6xfw",
"created_at":1595841536693,
"libelle":"Poppup interactives à effet immediat et isolé",
"prix":"0",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"dv9nnfEDtHtRQs8Hg"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"WNBwwg4R7hxrrkvXn",
"created_at":1595841624887,
"libelle":"Mise en memoire des actions utilisateurs tout au long d'une partie",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"AM6dsNTRge8dLwEcK"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"zEK7zGsAZm3SvXNXc",
"created_at":1595841687146,
"libelle":"Utilisation des données mises en mémoire pour un effet immediat et isolé",
"prix":"2",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"WsxvcqxQGxhCE65Py"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"cpbXqWuMgxHTb6JRk",
"created_at":1595841782408,
"libelle":"Mise en mémoire dans le but de reprendre une partie aprés fermeture/réouverture de l'application",
"prix":"2",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"hhkngSZtTba936RWJ"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"6ynLrghep2La3HCsS",
"created_at":1595841818752,
"libelle":"Score",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"4sXx4y3S4rw7NtqPQ"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"2vgRh7hGY6FL3YhRp",
"created_at":1595841818752,
"libelle":"Fonctionnement du jeu en ligne sans avoir à télécharger le scenario",
"prix":"2",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"SRJZXnvHh8NPsq4Zs",
"GPA3Rz9bXNjz8HvaX"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"9N4LT54f8hGjkCFNf",
"created_at":1595841818752,
"libelle":"Chronometre",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"aRqR2WffMn2EjWQid"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"HvnFcMQkgpvvHYr52",
"created_at":1595841818752,
"libelle":"Fonctionnement du jeu hors ligne après avoir téléchargé le scénario",
"prix":"2",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"7JhWWukixgAX5H8M4",
"L24gCj7edp42iZHeo"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"YSgzvr98BgPf7EB4E",
"created_at":1596181813454,
"libelle":"Saisie et creation d'un scenario ",
"prix":"",
"titre_lvl":"3",
"sans_interaction":true,
"numerique":false,
"logiques":[
"razWnwtLPMhWLAahe"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"WddzZKJCykR5DCsZ6",
"created_at":1596181882591,
"libelle":"Application mobile",
"prix":"",
"titre_lvl":"3",
"sans_interaction":true,
"numerique":false,
"logiques":[
"P5cwHvcsEg7wAx2s6"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"j8wuQ2gufqKbbxS5r",
"created_at":1596181980526,
"libelle":"Objet 15 combinaisons d'objets + réponse type pour les mauvaises combinaisons (avec image, texte, piste audio)",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":true,
"logiques":[
"imiksHCThiYS5L3EM",
"t3t3yr9LtzkdDBnZA"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"jEvuXPiNYwhyttPMo",
"created_at":1596181980526,
"libelle":" Complet 100 appels de piste audio possibilité de réponse en 3 étapes (avec image, texte, piste audio)",
"prix":"10",
"titre_lvl":"",
"sans_interaction":false,
"numerique":true,
"logiques":[
"JajbBRGkZgb4pijj6",
"xSrkrgTZwqT9PJ5BG",
"6bShWqPHT4kGtcf8f"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"y9ciExqKCc2Y6hxTK",
"created_at":1596182031625,
"libelle":"15 combinaisons d'objets + réponse type pour les mauvaises combinaisons (avec image, texte, piste audio)",
"prix":"2",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"dXbLnJyp37HwPLtZQ"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"dh3P6f4BBcbMsJFTn",
"created_at":1596182031625,
"libelle":"Light 100 appels de piste audio avec 1 seule réponse possible (avec image, texte, piste audio)",
"prix":"6",
"titre_lvl":"",
"sans_interaction":false,
"numerique":true,
"logiques":[
"qciDbLv9t3DFy8Lze",
"HFx2Jiojq8382yrrp",
"Fu98qh5y4cLWqifAm"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"x9SeoPKqbcKRQErHh",
"created_at":1596182031625,
"libelle":"Light 100 appels de piste audio avec 1 seule réponse possible (avec image, texte, piste audio)",
"prix":"2",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"q3rwX8LLEyAMeAS3Q",
"4fJbLnorqKo8ZNXaW",
"Ns9MGGv2NXtSJNjKR"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"7WqHLcZyK7wKaq5LR",
"created_at":1596182031625,
"libelle":" Complet 100 appels de piste audio possibilité de réponse en 3 étapes (avec image, texte, piste audio)",
"prix":"6",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"AFkJnjrdPjjsxcmCe",
"b7FSXWHLFnQvmMBb6"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"HMSqQESsFsk5mWuP9",
"created_at":1596182110872,
"libelle":"Vues ",
"prix":"",
"titre_lvl":"2",
"sans_interaction":true,
"numerique":false,
"logiques":[
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"aGoaCL7sudgXGTApu",
"created_at":1596182110872,
"libelle":"énigmes 15 énigmes + réponse type pour les propositions innexactes (avec image, texte, piste audio)",
"prix":"2",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"6APQ8WGwridfuNiap"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"M4YMdfWRztKQARi4b",
"created_at":1596182110872,
"libelle":"indices 40 à 50 indices (avec image, texte)",
"prix":"3",
"titre_lvl":"",
"sans_interaction":false,
"numerique":true,
"logiques":[
"HfDMEf8cSG2JL3ZYo",
"Ewqaeqxqe5FooYzaS",
"zfb9xZvu7MJ8NAXT3"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"8i95pgbY5NdAmufJw",
"created_at":1596182110872,
"libelle":"Deploiement",
"prix":"2",
"titre_lvl":"2",
"sans_interaction":false,
"numerique":false,
"logiques":[
"MuaaEANaaAeuabfdk"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"EdsZJk2mY9d329rsd",
"created_at":1596182110872,
"libelle":"Interface de saisie, création et modification/correction d'un scenario (Applicationweb)",
"prix":"",
"titre_lvl":"3",
"sans_interaction":true,
"numerique":false,
"logiques":[
"xzai6jDSh6XS6nKTu"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"B4n7FxnJFmiQoLGhD",
"created_at":1596182110872,
"libelle":"Elaboration du cahier des charges / maquette ",
"prix":"2",
"titre_lvl":"1",
"sans_interaction":false,
"numerique":false,
"logiques":[
"37g6feQsz42TnwPAi"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"2j4k3qGijetTDqjB2",
"created_at":1596182110872,
"libelle":"Conception",
"prix":"2",
"titre_lvl":"1",
"sans_interaction":false,
"numerique":false,
"logiques":[
"yNP7FPZQzgJefxGwu"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"9QhDtGA8E3Fg3mroz",
"created_at":1596182110872,
"libelle":"Elaboration du devis",
"prix":"2",
"titre_lvl":"1",
"sans_interaction":false,
"numerique":false,
"logiques":[
"F2kpkZkypAGtrYoKk"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"yN45tnXihFhv9zD3C",
"created_at":1596182110872,
"libelle":"Accueil",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"YhaBf7RJT8nWq8Zmm"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"rhaiPWJPurgFbEQuS",
"created_at":1596182110872,
"libelle":"Mise en place de l'architecture de l'application",
"prix":"3",
"titre_lvl":"1",
"sans_interaction":false,
"numerique":false,
"logiques":[
"9ACrkvNmiwCnuBXsR"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"3ouyaLPHMoEme6WEh",
"created_at":1596182110872,
"libelle":"Connexion",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":false,
"logiques":[
"QK2sEwrGESxqTxPjk"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"rdk6C5YRFPSqt2gcn",
"created_at":1596182110872,
"libelle":"énigmes 15 énigmes + réponse type pour les propositions innexactes (avec image, texte, piste audio)",
"prix":"1",
"titre_lvl":"",
"sans_interaction":false,
"numerique":true,
"logiques":[
"3R2Cuf3vgMtq5aWwz",
"9N7FXmD9dEsZr9cBr"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"A9Z8drBcFbdckzn2o",
"created_at":1596182110872,
"libelle":"indices 40 à 50 indices (avec image, texte)",
"prix":"2",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"knNFXrPjnTHMBoaAM",
"9bR6ZyYNh5wxAnFFM",
"RKfwAB8vLwt6vLv56"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"7yvfaP6haifxd2rTz",
"created_at":1596182110872,
"libelle":"indices 40 à 50 indices en 3 étapes (avec image, texte)",
"prix":"4",
"titre_lvl":"",
"sans_interaction":false,
"numerique":true,
"logiques":[
"g5HnoxhNw2sMWGJz7",
"jdsm26yARAQqBBp3q",
"GtCsk33vJeGRSrKWz"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"zNkhu33aqqv6oMB6F",
"created_at":1596182110872,
"libelle":"système de scroll infini sur toutes les pages (sauf connexion)",
"prix":"2",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"9vCAhvTWukTucixkj"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"rW2pe4kqGvRbQ47mP",
"created_at":1596182110872,
"libelle":"Responsive",
"prix":"4",
"titre_lvl":"2",
"sans_interaction":false,
"numerique":false,
"logiques":[
"RiKzQoYeiu2DHjYbd"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"hPDGaSauGewYuR6Hq",
"created_at":1596182110872,
"libelle":"Compatibilité multi navigateur chrome, firefox, IE edge, safari (version recentes)",
"prix":"8",
"titre_lvl":"2",
"sans_interaction":false,
"numerique":false,
"logiques":[
"jG3WzHXqdsgRQxwJy"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"h3WtaPmDjfwKYTEsx",
"created_at":1596182110872,
"libelle":"Système d'Upload de fichiers (images et sons)",
"prix":"4",
"titre_lvl":"2",
"sans_interaction":false,
"numerique":false,
"logiques":[
"ipQmKn6qQqbC86Y3M"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"cDcF7YTFzKZ4dJGHP",
"created_at":1596182110872,
"libelle":"Gestion des pistes audio",
"prix":"2",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"ajm7HY9K34ocaXgRp"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"mbH5YBu7nn97NtdRB",
"created_at":1596182110872,
"libelle":"Gestion des images",
"prix":"2",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"NkbdSTSk4kaErBGxn"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
},
{
"_id":"rw2H4CygCfCjGeAy9",
"created_at":1596182110872,
"libelle":"indices 40 à 50 indices en 3 étapes (avec image, texte)",
"prix":"3",
"titre_lvl":"0",
"sans_interaction":false,
"numerique":false,
"logiques":[
"TKnqnhte9iA5wuunc",
"g28weQAFLHaeETM4n",
"aRqzWNS97J2BBGbH8"
],
"dynamique":false,
"devis_id":"GabcZB9Jg2bsAhSov",
"user_id":"gofcmeaAhnAdyXFTf"
}
]









/////////////////////////////////////////////////////////////////////////////////////////////////////////
const LOGIQUES = [
{
"_id":"gru7vioNrCY6NyCNx",
"created_at":1596189493195,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"8aEEnnL5paPLtu9FG",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_===0",
"numerique_log":"0"
},
{
"_id":"8qaknNnDwfLMqu2AF",
"created_at":1596190540711,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"bfEHEFtmfcaroYLk5",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_===0",
"numerique_log":"0"
},
{
"_id":"4NEmTkD43XFxTfBnM",
"created_at":1596190570580,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"FrgcpETNkW8mWhDHr",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id20_===1||id21_===1",
"numerique_log":"1"
},
{
"_id":"57LvNr9yJ7WAkqsjE",
"created_at":1596271299469,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"Qy8QNsmqTKGK6Tzgh",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id3_===1||id2_===1",
"numerique_log":"0"
},
{
"_id":"K5xAq7FiHMq2buYPN",
"created_at":1596271358775,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"sE8LHiyYtAozqhKKW",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id1_===1||id3_===1",
"numerique_log":"0"
},
{
"_id":"EyxwRbZ5ojrq2a8db",
"created_at":1596271358775,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"sE8LHiyYtAozqhKKW",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id3_===0&&id2_===0&&id1_===0",
"numerique_log":"1"
},
{
"_id":"m8bX6jSBikQoi22qs",
"created_at":1596271363488,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"3GfFHZjSrKXd55x5W",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id1_===1||id2_===1",
"numerique_log":"0"
},
{
"_id":"w7zyAXjJTjjLcPL9N",
"created_at":1596271485728,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"Ksou4x4463Yi5FguJ",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id17_===1",
"numerique_log":"0"
},
{
"_id":"2szN82YwY3MHPqKBg",
"created_at":1596271509215,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"fJLMMMFcpL8pYWKou",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id16_===1",
"numerique_log":"0"
},
{
"_id":"sRvZNYkyD4k6rpjMf",
"created_at":1596272326609,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"xFuEKKpq92FkbuzY4",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id14_===1",
"numerique_log":"0"
},
{
"_id":"Awov4KoC6vroiqSp9",
"created_at":1596272349455,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"9cn28qoYFYCMTasGh",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id13_===0&&id14_===0",
"numerique_log":"1"
},
{
"_id":"3Hi2ja7tTLs8XyWTZ",
"created_at":1596272505644,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"P4kDnYy85LCGwMsPo",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id11_===1",
"numerique_log":"1"
},
{
"_id":"egdzDjDpL5QbuGikL",
"created_at":1596272556158,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"x4XaCWa9WBTw2dPZz",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id10_===0",
"numerique_log":"0"
},
{
"_id":"KJkPEw2gMJqEQDejP",
"created_at":1596272793621,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"5WfEAGjEhJDSz6Cmc",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"LFFd8wz3RSdCtXzjk",
"created_at":1596273019966,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"nbpXqHxE68Xw65zpB",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id6_"
},
{
"_id":"Y8cTxmFeRG84yX4ar",
"created_at":1596273123105,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"kBsAFZbCLE7fq89hw",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"x2XkuZ2sCkTgdxoid",
"created_at":1596273497002,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"q3KqMFHZxwxDBi8oM",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"236yCKbRfM7ahngjZ",
"created_at":1596273509904,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"3MBhNozbEEcdK2Xct",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"RP49eds5bF5C2kCu2",
"created_at":1596273528651,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"jN9LWutbEgRm635Ys",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"ai63YZZo3xu8eQpBD",
"created_at":1596273533195,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"PtchCLHofAXzb3ACq",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"HF9scDe2N8PBeByev",
"created_at":1596273581649,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"LkXAuZs8aDSGRZaDk",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"6aGCM2GpvjQCoekxK",
"created_at":1596273586718,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"S4AGDJ9Z2KA2vdxbz",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"EiTYSAyhHS2kYLuLv",
"created_at":1596273589690,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"WvgJCpANaRAidbGWG",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"hd3fLoKxF4haA6sH4",
"created_at":1596273596200,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"tPYSRgaCNwimssybj",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"ZY5CkfgF4DLWDxaeE",
"created_at":1596273601243,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"KgmpNYanP8ZeuMq3s",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"Z53XrocAbDMdbCbmA",
"created_at":1596273624058,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"JLXzQqfy6WiPERrFN",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id5_",
"numerique_log":""
},
{
"_id":"MeAE4ArDEy2qdE3as",
"created_at":1596273638250,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"pka5KSANZQhHcKu4t",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id5_",
"numerique_log":""
},
{
"_id":"45eP9sbfZPW7ZTtSn",
"created_at":1596273645076,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"Kpo6dKEWZ8tqoq6ZC",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id5_",
"numerique_log":""
},
{
"_id":"t78PCyh8H7k3n47pX",
"created_at":1596273657821,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"DncG4BRd9CRnCvfmj",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id5_",
"numerique_log":""
},
{
"_id":"jDbcsjXzFhZ3zHBDc",
"created_at":1596273661491,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"yLACgcCgqkatzuFfd",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id5_",
"numerique_log":""
},
{
"_id":"Fi7hmmXc6rQNWgiHx",
"created_at":1596273789147,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"K7Z9SKmWMia3so6SC",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"9YuCfmXdt7vTtSb9k",
"created_at":1596274008345,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"AdTEJKuiMRRFX4XiM",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"dv9nnfEDtHtRQs8Hg",
"created_at":1596274041034,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"TWAgRS6SYGorC6xfw",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"AM6dsNTRge8dLwEcK",
"created_at":1596274081117,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"WNBwwg4R7hxrrkvXn",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id10_",
"numerique_log":""
},
{
"_id":"WsxvcqxQGxhCE65Py",
"created_at":1596274119634,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"zEK7zGsAZm3SvXNXc",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id10_",
"numerique_log":""
},
{
"_id":"hhkngSZtTba936RWJ",
"created_at":1596274204403,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"cpbXqWuMgxHTb6JRk",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id11_",
"numerique_log":""
},
{
"_id":"SRJZXnvHh8NPsq4Zs",
"created_at":1596410095559,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"2vgRh7hGY6FL3YhRp",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id1_===1||id3_===1",
"numerique_log":"1"
},
{
"_id":"GPA3Rz9bXNjz8HvaX",
"created_at":1596410315345,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"2vgRh7hGY6FL3YhRp",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id2_===1",
"numerique_log":"0"
},
{
"_id":"7JhWWukixgAX5H8M4",
"created_at":1596410472917,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"HvnFcMQkgpvvHYr52",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id2_===1||id3_===1",
"numerique_log":"1"
},
{
"_id":"L24gCj7edp42iZHeo",
"created_at":1596410487656,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"HvnFcMQkgpvvHYr52",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id1_===1",
"numerique_log":"0"
},
{
"_id":"FxfaLnnrhQ8AME5nd",
"created_at":1596412423328,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"Qy8QNsmqTKGK6Tzgh",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id3_===0&&id2_===0&&id1_===0",
"numerique_log":"1"
},
{
"_id":"oTJkJgFvwsP6bohDC",
"created_at":1596412576109,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"3GfFHZjSrKXd55x5W",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id3_===0&&id2_===0&&id1_===0",
"numerique_log":"1"
},
{
"_id":"aRqR2WffMn2EjWQid",
"created_at":1596412878219,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"9N4LT54f8hGjkCFNf",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id7_"
},
{
"_id":"4sXx4y3S4rw7NtqPQ",
"created_at":1596412917282,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"6ynLrghep2La3HCsS",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id8_"
},
{
"_id":"qciDbLv9t3DFy8Lze",
"created_at":1596413252880,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"dh3P6f4BBcbMsJFTn",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id13_===1&&id18_"
},
{
"_id":"imiksHCThiYS5L3EM",
"created_at":1596444699431,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"j8wuQ2gufqKbbxS5r",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id18_"
},
{
"_id":"JajbBRGkZgb4pijj6",
"created_at":1596445635357,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"jEvuXPiNYwhyttPMo",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id14_===1&&id18_"
},
{
"_id":"HFx2Jiojq8382yrrp",
"created_at":1596445699200,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"dh3P6f4BBcbMsJFTn",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id14_===1",
"numerique_log":"0"
},
{
"_id":"xSrkrgTZwqT9PJ5BG",
"created_at":1596445764641,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"jEvuXPiNYwhyttPMo",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id13_===1",
"numerique_log":"0"
},
{
"_id":"3R2Cuf3vgMtq5aWwz",
"created_at":1596446002244,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"rdk6C5YRFPSqt2gcn",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id18_",
"numerique_log":""
},
{
"_id":"HfDMEf8cSG2JL3ZYo",
"created_at":1596446032269,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"M4YMdfWRztKQARi4b",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id16_===1&&id18_",
"numerique_log":""
},
{
"_id":"g5HnoxhNw2sMWGJz7",
"created_at":1596446137864,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"7yvfaP6haifxd2rTz",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id17_===1&&id18_",
"numerique_log":""
},
{
"_id":"Ewqaeqxqe5FooYzaS",
"created_at":1596446192263,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"M4YMdfWRztKQARi4b",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id17_===1",
"numerique_log":"0"
},
{
"_id":"jdsm26yARAQqBBp3q",
"created_at":1596446421975,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"7yvfaP6haifxd2rTz",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id16_===1",
"numerique_log":"0"
},
{
"_id":"Fu98qh5y4cLWqifAm",
"created_at":1596446618386,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"dh3P6f4BBcbMsJFTn",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_===1",
"numerique_log":"",
"prix_log":"3"
},
{
"_id":"6bShWqPHT4kGtcf8f",
"created_at":1596446646746,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"jEvuXPiNYwhyttPMo",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_===1",
"numerique_log":"",
"prix_log":"5"
},
{
"_id":"t3t3yr9LtzkdDBnZA",
"created_at":1596446658911,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"j8wuQ2gufqKbbxS5r",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_===1",
"numerique_log":"",
"prix_log":"0.5"
},
{
"_id":"9N7FXmD9dEsZr9cBr",
"created_at":1596446704760,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"rdk6C5YRFPSqt2gcn",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_===1",
"numerique_log":"",
"prix_log":"0.5"
},
{
"_id":"zfb9xZvu7MJ8NAXT3",
"created_at":1596446718662,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"M4YMdfWRztKQARi4b",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_===1",
"numerique_log":"",
"prix_log":"1.5"
},
{
"_id":"GtCsk33vJeGRSrKWz",
"created_at":1596446740579,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"7yvfaP6haifxd2rTz",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_===1",
"numerique_log":"",
"prix_log":"2"
},
{
"_id":"37g6feQsz42TnwPAi",
"created_at":1596448706392,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"B4n7FxnJFmiQoLGhD",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_"
},
{
"_id":"yNP7FPZQzgJefxGwu",
"created_at":1596448751425,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"2j4k3qGijetTDqjB2",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_"
},
{
"_id":"F2kpkZkypAGtrYoKk",
"created_at":1596448761352,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"9QhDtGA8E3Fg3mroz",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_"
},
{
"_id":"9ACrkvNmiwCnuBXsR",
"created_at":1596448784472,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"rhaiPWJPurgFbEQuS",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_"
},
{
"_id":"QK2sEwrGESxqTxPjk",
"created_at":1596448798382,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"3ouyaLPHMoEme6WEh",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_"
},
{
"_id":"YhaBf7RJT8nWq8Zmm",
"created_at":1596448804648,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"yN45tnXihFhv9zD3C",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_"
},
{
"_id":"q3rwX8LLEyAMeAS3Q",
"created_at":1596448807501,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"x9SeoPKqbcKRQErHh",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_&&id13_===1"
},
{
"_id":"AFkJnjrdPjjsxcmCe",
"created_at":1596448889329,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"7WqHLcZyK7wKaq5LR",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id14_===1&&id19_"
},
{
"_id":"4fJbLnorqKo8ZNXaW",
"created_at":1596448942746,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"x9SeoPKqbcKRQErHh",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id14_===1",
"numerique_log":"0"
},
{
"_id":"b7FSXWHLFnQvmMBb6",
"created_at":1596448972615,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"7WqHLcZyK7wKaq5LR",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id13_===1",
"numerique_log":"0"
},
{
"_id":"Ns9MGGv2NXtSJNjKR",
"created_at":1596449038088,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"x9SeoPKqbcKRQErHh",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id13_===1&&id19_"
},
{
"_id":"dBgyagHuftNZcEt7B",
"created_at":1596449094108,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"Ksou4x4463Yi5FguJ",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id16_===0&&id17_===0",
"numerique_log":"1"
},
{
"_id":"jQHqu6f8K9G2mkQqK",
"created_at":1596449114815,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"fJLMMMFcpL8pYWKou",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id17_===0&&id16_===0",
"numerique_log":"1"
},
{
"_id":"jrM2ChjDJvBnLSW9p",
"created_at":1596449283401,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"xFuEKKpq92FkbuzY4",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id13_===0&&id14_===0",
"numerique_log":"1"
},
{
"_id":"g9XfgtgZcyHPMvDrS",
"created_at":1596449343254,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"9cn28qoYFYCMTasGh",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id13_===1",
"numerique_log":"0"
},
{
"_id":"dXbLnJyp37HwPLtZQ",
"created_at":1596534480605,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"y9ciExqKCc2Y6hxTK",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_"
},
{
"_id":"6APQ8WGwridfuNiap",
"created_at":1596534499579,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"aGoaCL7sudgXGTApu",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_"
},
{
"_id":"knNFXrPjnTHMBoaAM",
"created_at":1596534552606,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"A9Z8drBcFbdckzn2o",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id16_===1&&id19_",
"numerique_log":""
},
{
"_id":"TKnqnhte9iA5wuunc",
"created_at":1596534603036,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"rw2H4CygCfCjGeAy9",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id17_===1&&id19_",
"numerique_log":""
},
{
"_id":"9bR6ZyYNh5wxAnFFM",
"created_at":1596534767773,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"A9Z8drBcFbdckzn2o",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id17_===1",
"numerique_log":"0"
},
{
"_id":"g28weQAFLHaeETM4n",
"created_at":1596534810453,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"rw2H4CygCfCjGeAy9",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id16_===1",
"numerique_log":"0"
},
{
"_id":"aRqzWNS97J2BBGbH8",
"created_at":1596534875307,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"rw2H4CygCfCjGeAy9",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id17_===1&&id19_===0",
"numerique_log":"0"
},
{
"_id":"RKfwAB8vLwt6vLv56",
"created_at":1596534918473,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"A9Z8drBcFbdckzn2o",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id16_===1&&id19_===0",
"numerique_log":"0"
},
{
"_id":"NkbdSTSk4kaErBGxn",
"created_at":1596535041081,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"mbH5YBu7nn97NtdRB",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_",
"numerique_log":""
},
{
"_id":"ajm7HY9K34ocaXgRp",
"created_at":1596535048667,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"cDcF7YTFzKZ4dJGHP",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_",
"numerique_log":""
},
{
"_id":"9vCAhvTWukTucixkj",
"created_at":1596535061613,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"zNkhu33aqqv6oMB6F",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_",
"numerique_log":""
},
{
"_id":"RiKzQoYeiu2DHjYbd",
"created_at":1596535083337,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"rW2pe4kqGvRbQ47mP",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id20_",
"numerique_log":""
},
{
"_id":"jG3WzHXqdsgRQxwJy",
"created_at":1596535105578,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"hPDGaSauGewYuR6Hq",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id21_",
"numerique_log":""
},
{
"_id":"ipQmKn6qQqbC86Y3M",
"created_at":1596535127306,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"h3WtaPmDjfwKYTEsx",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_",
"numerique_log":""
},
{
"_id":"MuaaEANaaAeuabfdk",
"created_at":1596535140167,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"8i95pgbY5NdAmufJw",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_",
"numerique_log":""
},
{
"_id":"P5cwHvcsEg7wAx2s6",
"created_at":1596542920645,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"WddzZKJCykR5DCsZ6",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"CnAd6PvvmRGLYbtXn",
"created_at":1596542972063,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"T5hN8Ws2m9ktWx7fH",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"eh7XLXNEX7RAmwrh7",
"created_at":1596542979402,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"8YpF53hGhsGhrZFSx",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id5_",
"numerique_log":""
},
{
"_id":"rafeNpQqJrdePqd44",
"created_at":1596542984192,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"JxfjFerDi3xqnbcE2",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"true",
"numerique_log":"1"
},
{
"_id":"razWnwtLPMhWLAahe",
"created_at":1596542994375,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"YSgzvr98BgPf7EB4E",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id18_",
"numerique_log":""
},
{
"_id":"xzai6jDSh6XS6nKTu",
"created_at":1596543051963,
"devis_id":"GabcZB9Jg2bsAhSov",
"element_id":"EdsZJk2mY9d329rsd",
"user_id":"gofcmeaAhnAdyXFTf",
"libelle_log":"id19_",
"numerique_log":""
}]

const CHOIX = {
"_id":"mkMiNm8zr6Y3r8XZF",
"created_at":1597058265993,
"user_id":"gofcmeaAhnAdyXFTf",
"devis_id":"GabcZB9Jg2bsAhSov",
"elements":{
"kBsAFZbCLE7fq89hw":1,
"5WfEAGjEhJDSz6Cmc":1,
"3GfFHZjSrKXd55x5W":0,
"pnRuvjM5Lk6LMX3ro":0,
"Sk96LT397ev2BfQMn":0,
"TuFXrPjMEm9k5QCsf":0,
"dpRYqjzifbXSK9tDk":0,
"sE8LHiyYtAozqhKKW":1,
"nbpXqHxE68Xw65zpB":0,
"q3KqMFHZxwxDBi8oM":1,
"3MBhNozbEEcdK2Xct":1,
"jN9LWutbEgRm635Ys":1,
"PtchCLHofAXzb3ACq":1,
"JxfjFerDi3xqnbcE2":1,
"yLACgcCgqkatzuFfd":0,
"pka5KSANZQhHcKu4t":0,
"JLXzQqfy6WiPERrFN":0,
"DncG4BRd9CRnCvfmj":0,
"LkXAuZs8aDSGRZaDk":1,
"S4AGDJ9Z2KA2vdxbz":1,
"Kpo6dKEWZ8tqoq6ZC":0,
"T5hN8Ws2m9ktWx7fH":1,
"WvgJCpANaRAidbGWG":1,
"tPYSRgaCNwimssybj":1,
"KgmpNYanP8ZeuMq3s":1,
"8YpF53hGhsGhrZFSx":0,
"K7Z9SKmWMia3so6SC":1,
"AdTEJKuiMRRFX4XiM":1,
"TWAgRS6SYGorC6xfw":1,
"WNBwwg4R7hxrrkvXn":0,
"zEK7zGsAZm3SvXNXc":0,
"cpbXqWuMgxHTb6JRk":0,
"6ynLrghep2La3HCsS":0,
"2vgRh7hGY6FL3YhRp":0,
"Qy8QNsmqTKGK6Tzgh":0,
"9N4LT54f8hGjkCFNf":0,
"HvnFcMQkgpvvHYr52":1,
"YSgzvr98BgPf7EB4E":0,
"WddzZKJCykR5DCsZ6":1,
"j8wuQ2gufqKbbxS5r":0,
"y9ciExqKCc2Y6hxTK":0,
"HMSqQESsFsk5mWuP9":0,
"aGoaCL7sudgXGTApu":0,
"M4YMdfWRztKQARi4b":0,
"8i95pgbY5NdAmufJw":0,
"EdsZJk2mY9d329rsd":0,
"B4n7FxnJFmiQoLGhD":0,
"2j4k3qGijetTDqjB2":0,
"9QhDtGA8E3Fg3mroz":0,
"yN45tnXihFhv9zD3C":0,
"rhaiPWJPurgFbEQuS":0,
"3ouyaLPHMoEme6WEh":0,
"dh3P6f4BBcbMsJFTn":0,
"x9SeoPKqbcKRQErHh":0,
"rdk6C5YRFPSqt2gcn":0,
"A9Z8drBcFbdckzn2o":0,
"7yvfaP6haifxd2rTz":0,
"zNkhu33aqqv6oMB6F":0,
"rW2pe4kqGvRbQ47mP":0,
"hPDGaSauGewYuR6Hq":0,
"h3WtaPmDjfwKYTEsx":0,
"jEvuXPiNYwhyttPMo":0,
"7WqHLcZyK7wKaq5LR":0,
"cDcF7YTFzKZ4dJGHP":0,
"mbH5YBu7nn97NtdRB":0,
"rw2H4CygCfCjGeAy9":0,
"fztcTn6wE7zFvvNwR":0,
"hKdnv6WY8BziTRnLM":0,
"NyEoMcMnyquawcTNy":0,
"AeT4yA5aQ8neCGqgy":0,
"P4kDnYy85LCGwMsPo":0,
"8aEEnnL5paPLtu9FG":0,
"x4XaCWa9WBTw2dPZz":0,
"vX5SKwTKHrKf7SCzg":0,
"xFuEKKpq92FkbuzY4":1,
"Ksou4x4463Yi5FguJ":1,
"9cn28qoYFYCMTasGh":0,
"ejzakZceuW432HzBE":0,
"fJLMMMFcpL8pYWKou":0,
"zNB9eYodKniy2MPd9":0,
"yMdG7cCsswskiWG8o":0,
"FrgcpETNkW8mWhDHr":0,
"bfEHEFtmfcaroYLk5":0,
"dqXtDgDPHrhFRuMJs":0
}}	

export {
	DEVIS,ELEMENTS,LOGIQUES,CHOIX
};
